name: Flutter Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        if: matrix.platform == 'android'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # Ensure this version includes Dart SDK 3.5.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Android
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Upload Android APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk