name: Flutter Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, web]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        if: matrix.platform == 'android'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Android
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Upload Android APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Build for Web
      #   if: matrix.platform == 'web'
      #   run: flutter build web --release

      # - name: Deploy to GitHub Pages
      #   if: matrix.platform == 'web'
      #   uses: peaceiris/actions-gh-pages@v3