name: Flutter Multi-Platform Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, web]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # Substitua pela versão do Flutter que você está usando

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Android
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Upload Android APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build for Web
        if: matrix.platform == 'web'
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        if: matrix.platform == 'web'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web